/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.question;

import java.io.Serializable;

/**
 *
 * @author Alumno Tarde
 */
public class Question extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form Question
     */
    public Question() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rBRespuesta1 = new javax.swing.JRadioButton();
        rBRespuesta2 = new javax.swing.JRadioButton();
        rBRespuesta3 = new javax.swing.JRadioButton();
        rBRespuesta4 = new javax.swing.JRadioButton();
        numeroPregunta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();

        buttonGroup1.add(rBRespuesta1);
        rBRespuesta1.setText("Respuesta 1");
        rBRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBRespuesta1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBRespuesta2);
        rBRespuesta2.setText("Respuesta 2");

        buttonGroup1.add(rBRespuesta3);
        rBRespuesta3.setText("Respuesta 3");

        buttonGroup1.add(rBRespuesta4);
        rBRespuesta4.setText("Respuesta 4");
        rBRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBRespuesta4ActionPerformed(evt);
            }
        });

        numeroPregunta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numeroPregunta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numeroPregunta.setText("1.");

        jTextField1.setText("Pregunta");
        jTextField1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(rBRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBRespuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBRespuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(numeroPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(numeroPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBRespuesta1)
                .addGap(18, 18, 18)
                .addComponent(rBRespuesta2)
                .addGap(18, 18, 18)
                .addComponent(rBRespuesta3)
                .addGap(18, 18, 18)
                .addComponent(rBRespuesta4)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rBRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBRespuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBRespuesta1ActionPerformed

    private void rBRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBRespuesta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBRespuesta4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel numeroPregunta;
    private javax.swing.JRadioButton rBRespuesta1;
    private javax.swing.JRadioButton rBRespuesta2;
    private javax.swing.JRadioButton rBRespuesta3;
    private javax.swing.JRadioButton rBRespuesta4;
    // End of variables declaration//GEN-END:variables
}
