/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.question;

import java.io.Serializable;

/**
 *
 * @author Alumno Tarde
 */
public class Question extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form Question
     */
    public Question() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rBRespuesta1 = new javax.swing.JRadioButton();
        rBRespuesta2 = new javax.swing.JRadioButton();
        rBRespuesta3 = new javax.swing.JRadioButton();
        rBRespuesta4 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 67));
        setMinimumSize(new java.awt.Dimension(400, 67));
        setPreferredSize(new java.awt.Dimension(400, 67));
        setRequestFocusEnabled(false);

        buttonGroup1.add(rBRespuesta1);
        rBRespuesta1.setText("Respuesta 1");
        rBRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBRespuesta1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBRespuesta2);
        rBRespuesta2.setText("Respuesta 2");

        buttonGroup1.add(rBRespuesta3);
        rBRespuesta3.setText("Respuesta 3");

        buttonGroup1.add(rBRespuesta4);
        rBRespuesta4.setText("Respuesta 4");
        rBRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBRespuesta4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("1.");

        jLabel2.setText("<html><p>Texto de la pregunta que es totalmente aleatorio ahdjajij  iajasij dijwi wij diwjdiwjdio jao ddijdiwa woijd iwioajdoajidjwijdiwad</p> </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBRespuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBRespuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBRespuesta1)
                .addGap(18, 18, 18)
                .addComponent(rBRespuesta2)
                .addGap(18, 18, 18)
                .addComponent(rBRespuesta3)
                .addGap(18, 18, 18)
                .addComponent(rBRespuesta4)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rBRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBRespuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBRespuesta1ActionPerformed

    private void rBRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBRespuesta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBRespuesta4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rBRespuesta1;
    private javax.swing.JRadioButton rBRespuesta2;
    private javax.swing.JRadioButton rBRespuesta3;
    private javax.swing.JRadioButton rBRespuesta4;
    // End of variables declaration//GEN-END:variables
}
